version: '2'
services:
  serial:
    build: ./sensor
    restart: always
    privileged: true
    network_mode: "host"
    devices:
      - "/dev:/dev"
    labels:
      io.balena.features.sysfs: '1'
    environment:
      DEBUG: "sensor"
